# Generated by Django 5.2.2 on 2025-06-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-publication_date']},
        ),
    ]
