# Generated by Django 5.2.2 on 2025-07-15 21:11

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', accounts.managers.UserCustomManager()),
            ],
        ),
    ]
