# Generated by Django 5.2.2 on 2025-06-14 20:07

import django.core.validators
import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[photos.validators.validate_field_size])),
                ('description', models.TextField(max_length=300, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(max_length=30)),
                ('publication_date', models.DateField(auto_now=True)),
                ('tagged_pet', models.ManyToManyField(blank=True, to='pets.pet')),
            ],
        ),
    ]
