# Generated by Django 5.2.2 on 2025-06-25 19:24

import photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='files', validators=[photos.validators.validate_field_size]),
        ),
    ]
